/*
 * frmLogin.java
 *
 * Created on July 26, 2006, 9:56 AM
 */

package rwframework;
import rwframework.controls.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.*;
import java.io.*;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author  destes
 */
public class frmLogin extends javax.swing.JFrame {
    
    /** Creates new form frmLogin */
    public cDataHandler DataHandler;
    public cDataHandler DatabaseInfo;
    String database;
    public ArrayList CompanyList = new ArrayList();
    
    public frmLogin(cDataHandler DataHandle) {
        DataHandler = DataHandle;
        database = DataHandler.database;
        initComponents();
        this.getContentPane().setBackground(java.awt.Color.DARK_GRAY);
        InitializeConnection();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCompany = new javax.swing.JComboBox();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        cmdlogin = new javax.swing.JButton();
        cmdclose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        cmdConfig = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Redwind Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        cmbCompany.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCompanyActionPerformed(evt);
            }
        });

        txtusername.setFont(new java.awt.Font("Arial", 0, 14));
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });

        txtpassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });

        cmdlogin.setBackground(new java.awt.Color(200, 200, 200));
        cmdlogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmdlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rwframework/images/icons/key_go.png"))); // NOI18N
        cmdlogin.setMnemonic('l');
        cmdlogin.setText("Login");
        cmdlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdloginActionPerformed(evt);
            }
        });

        cmdclose.setBackground(new java.awt.Color(200, 200, 200));
        cmdclose.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmdclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rwframework/images/icons/stop.png"))); // NOI18N
        cmdclose.setMnemonic('c');
        cmdclose.setText("Close");
        cmdclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Company:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UserName:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");

        cmdConfig.setBackground(new java.awt.Color(200, 200, 200));
        cmdConfig.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmdConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rwframework/images/icons/pencil.png"))); // NOI18N
        cmdConfig.setText("Configure");
        cmdConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConfigActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rwframework/images/redwind-logo.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(79, 79, 79)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(txtpassword)
                            .add(txtusername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(cmdclose, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                        .add(cmdlogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(cmdConfig, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(334, 334, 334))
            .add(layout.createSequentialGroup()
                .add(81, 81, 81)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(cmbCompany, 0, 191, Short.MAX_VALUE)
                .add(326, 326, 326))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jLabel4)
                .add(49, 49, 49)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cmbCompany, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txtusername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(txtpassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cmdclose)
                    .add(cmdlogin))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(cmdConfig)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-390)/2, (screenSize.height-428)/2, 390, 428);
    }// </editor-fold>//GEN-END:initComponents
    public void InitializeConnection()
    {
        database = DataHandler.database;
        this.cmbCompany.removeAllItems();
        CompanyList = new ArrayList();
        try
        {
            if(DataHandler.error==true){
                throw new Exception("Unable to load Configuration file.");
            }
            System.out.println("Attempting Connection: " + DataHandler.GetConURL());
            rwframework.models.Company Companies = new rwframework.models.Company(this.DataHandler);
            ArrayList myResults = Companies.find_all("application = 'rmms'","name ASC");
            for(int x=0;x<myResults.size();x++)
            {
                ArrayList ResultsList = new ArrayList();
                rwframework.controls.DCOMActiveRecord rst = (rwframework.controls.DCOMActiveRecord)(myResults.get(x));
                String CompanyName;
                CompanyName = rst.getValue("name");
                ResultsList.add(rst.getValue("id"));
                ResultsList.add(CompanyName);
                ResultsList.add(rst.getValue("catalog_name"));
                ResultsList.add(rst.getValue("address"));
                ResultsList.add(rst.getValue("address_2"));
                ResultsList.add(rst.getValue("city"));
                ResultsList.add(rst.getValue("state"));
                ResultsList.add(rst.getValue("zip"));
                ResultsList.add(rst.getValue("phone"));
                CompanyList.add(ResultsList);
                if(x==0)
                    DataHandler.database = rst.getValue("catalog_name");
                this.cmbCompany.addItem(CompanyName);
                
                
            }
            
            cmdlogin.setEnabled(true);
        } catch (SQLException ex)
        {
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
            cmdlogin.setEnabled(false);
            JOptionPane.showMessageDialog(this,"There was an error connecting to the database, please check configuration.");
        }catch(Exception e){
            System.out.println(e.toString());
            cmdlogin.setEnabled(false);
            JOptionPane.showMessageDialog(this,"The configuation file is corrupt or missing, please re-configure.");
        }
    }
    private void cmdConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConfigActionPerformed
// TODO add your handling code here:
        frmConfig ConfigFrame = new frmConfig(DataHandler, database);
        ConfigFrame.setModal(true);
        
        ConfigFrame.setVisible(true);
        if(ConfigFrame.cancel == false)
            InitializeConnection();
        
    }//GEN-LAST:event_cmdConfigActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        this.txtusername.requestFocus();
    }//GEN-LAST:event_formComponentShown

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
// TODO add your handling code here:
        cmdloginActionPerformed(null);
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
// TODO add your handling code here:
        this.txtpassword.requestFocus();
    }//GEN-LAST:event_txtusernameActionPerformed

    private void cmbCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCompanyActionPerformed
        if(cmbCompany.getSelectedIndex() > - 0 && CompanyList.size() >- cmbCompany.getSelectedIndex()-1)
        DataHandler.database = ((ArrayList)CompanyList.get(cmbCompany.getSelectedIndex())).get(2).toString();
        this.txtusername.requestFocus();
    }//GEN-LAST:event_cmbCompanyActionPerformed

    private void cmdloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdloginActionPerformed
// TODO add your handling code here:
        rwframework.models.User MainUser;
        cDataHandler newDataHandler = new cDataHandler(DataHandler.ErrorHandler);
        try{
        newDataHandler.loadSettings("config.xml");
        }
        catch(Exception e)
        {
         DataHandler.ErrorHandler.printLog("frmLogin","cmdloginActionPerformed()",e.toString());   
        }
        newDataHandler.database = DataHandler.database;

        MainUser = new rwframework.models.User(newDataHandler);
        if(MainUser.Validate(this.txtusername.getText(),this.txtpassword.getText()))
        {
            this.setVisible(false);
            rwframework.models.Company CurrentCompany = new rwframework.models.Company(DataHandler);
            CurrentCompany.setValue("id",((ArrayList)CompanyList.get(cmbCompany.getSelectedIndex())).get(0).toString());
            CurrentCompany.load();
            Application MainFrame = new Application(newDataHandler,CurrentCompany,MainUser);
          //  frmMainFrame MainFrame = new frmMainFrame(DataHandler,MainUser,(String)this.cmbCompany.getSelectedItem());
          
            MainFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
            MainFrame.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Invalid Username/Password...Try Again!");
            this.txtpassword.setSelectionStart(0);
            this.txtpassword.setSelectionEnd(this.txtpassword.getText().length());
            this.txtpassword.requestFocus();
            try
            {
            newDataHandler.GetConnection().close();
            }
            catch(SQLException ex)
            {
                
            }
        }
        
    }//GEN-LAST:event_cmdloginActionPerformed

    private void cmdcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcloseActionPerformed
// TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmdcloseActionPerformed
    
    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCompany;
    private javax.swing.JButton cmdConfig;
    private javax.swing.JButton cmdclose;
    private javax.swing.JButton cmdlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
    
}
