/*
 * frmSplash.java
 *
 * Created on July 26, 2006, 9:52 PM
 */

package rwframework;
import java.util.Timer;
import java.util.TimerTask;
/**
 *
 * @author  destes
 */
public class frmSplash extends javax.swing.JDialog {
    
    /** Creates new form frmSplash */
    public frmSplash() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rwframework/images/splash.png"))); // NOI18N
        getContentPane().add(jLabel1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-593)/2, (screenSize.height-296)/2, 593, 296);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
                Timer timer = new Timer();
        timer.schedule(new RemindTask(this), 3*1000);
    }//GEN-LAST:event_formWindowOpened
    class RemindTask extends TimerTask {
        public frmSplash SplashF;
        public RemindTask(frmSplash thesplash)
        {
            SplashF = thesplash;
        }
        public void run() {
                            SplashF.setVisible(false);
                            SplashF.dispose();
           	       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSplash().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
